<a href="https://colab.research.google.com/github/MarioArango/Indepsoft/blob/master/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from google.colab import drive

In [ ]:
drive.mount('/content/gdrive')
path_data = "/content/gdrive/My Drive/Practicando/"
df = pd.read_csv(path_data+'FastFoodRestaurants.csv')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [ ]:
#Si la tabla CSV, ya tiene una columna "-id" que identifica a cada fila, como una bd, entonces podemos decirle a pandas, oye toma esa columna como identificador
#df = pd.read_csv(path_data+'FastFoodRestaurants.csv', index_col="_id")

In [ ]:
df

                    address  ...                                           websites
0               324 Main St  ...  http://mcdonalds.com,http://www.mcdonalds.com/...
1           530 Clinton Ave  ...                              http://www.wendys.com
2      408 Market Square Dr  ...  http://www.frischs.com,https://www.frischs.com...
3     6098 State Highway 37  ...  http://mcdonalds.com,http://www.mcdonalds.com/...
4           139 Columbus Rd  ...  http://www.omgrotisserie.com,http://omgrotisse...
...                     ...  ...                                                ...
9995  3013 Peach Orchard Rd  ...            http://www.wendys.com,http://wendys.com
9996      678 Northwest Hwy  ...                           http://www.mcdonalds.com
9997           1708 Main St  ...                                http://fiveguys.com
9998      67740 Highway 111  ...  http://www.elpolloloco.com,http://elpolloloco.com
9999    5701 E La Palma Ave  ...                             http://www.carlsjr.com

[10000 rows x 10 columns]

**Para ver las 5 primeras filas, por defecto / df.head(filas)**

In [ ]:
df.head()

                 address  ...                                           websites
0            324 Main St  ...  http://mcdonalds.com,http://www.mcdonalds.com/...
1        530 Clinton Ave  ...                              http://www.wendys.com
2   408 Market Square Dr  ...  http://www.frischs.com,https://www.frischs.com...
3  6098 State Highway 37  ...  http://mcdonalds.com,http://www.mcdonalds.com/...
4        139 Columbus Rd  ...  http://www.omgrotisserie.com,http://omgrotisse...

[5 rows x 10 columns]

**Muesta las 5 últimas filas, por defecto / df.tail(filas)**

In [ ]:
df.tail()

                    address  ...                                           websites
9995  3013 Peach Orchard Rd  ...            http://www.wendys.com,http://wendys.com
9996      678 Northwest Hwy  ...                           http://www.mcdonalds.com
9997           1708 Main St  ...                                http://fiveguys.com
9998      67740 Highway 111  ...  http://www.elpolloloco.com,http://elpolloloco.com
9999    5701 E La Palma Ave  ...                             http://www.carlsjr.com

[5 rows x 10 columns]

**Hace calculos estadísticos en las propiedades con valores numéricos / df.describe()**

In [ ]:
df.describe()

           latitude     longitude
count  10000.000000  10000.000000
mean      37.552195    -91.056132
std        5.050275     18.556339
min       -6.244273   -159.378915
25%       34.028706    -97.412631
50%       38.298217    -87.660930
75%       41.116765    -81.458351
max       64.840240    123.012361

**Limpieza de datos, es cuando existen valores vacios "NaN", df.dropna()**

In [ ]:
#Retorna la el dataframe filtrado, sin filas con valores NaN, el df original no sufre cambios
df_filtrado = df.dropna()
df_filtrado

                    address  ...                                           websites
0               324 Main St  ...  http://mcdonalds.com,http://www.mcdonalds.com/...
1           530 Clinton Ave  ...                              http://www.wendys.com
2      408 Market Square Dr  ...  http://www.frischs.com,https://www.frischs.com...
3     6098 State Highway 37  ...  http://mcdonalds.com,http://www.mcdonalds.com/...
4           139 Columbus Rd  ...  http://www.omgrotisserie.com,http://omgrotisse...
...                     ...  ...                                                ...
9995  3013 Peach Orchard Rd  ...            http://www.wendys.com,http://wendys.com
9996      678 Northwest Hwy  ...                           http://www.mcdonalds.com
9997           1708 Main St  ...                                http://fiveguys.com
9998      67740 Highway 111  ...  http://www.elpolloloco.com,http://elpolloloco.com
9999    5701 E La Palma Ave  ...                             http://www.carlsjr.com

[9535 rows x 10 columns]

**Si no queremos eliminar los NaN, y ponerle un valor fijo a todos los vacios / df.fillna(valor)**

In [ ]:
#Devuelve el valor, la original no sufre cambios
df_filtrado = df.fillna(0)
#Para evitar poner valores por defecto en el NaN que no sean en mismo tipo de datos de la columna que los reprensta el parámetro sera un diccionario
df_filtrado = df.fillna({"latitude": 0, "longitude": 0, "websites": " " })
df_filtrado

                    address  ...                                           websites
0               324 Main St  ...  http://mcdonalds.com,http://www.mcdonalds.com/...
1           530 Clinton Ave  ...                              http://www.wendys.com
2      408 Market Square Dr  ...  http://www.frischs.com,https://www.frischs.com...
3     6098 State Highway 37  ...  http://mcdonalds.com,http://www.mcdonalds.com/...
4           139 Columbus Rd  ...  http://www.omgrotisserie.com,http://omgrotisse...
...                     ...  ...                                                ...
9995  3013 Peach Orchard Rd  ...            http://www.wendys.com,http://wendys.com
9996      678 Northwest Hwy  ...                           http://www.mcdonalds.com
9997           1708 Main St  ...                                http://fiveguys.com
9998      67740 Highway 111  ...  http://www.elpolloloco.com,http://elpolloloco.com
9999    5701 E La Palma Ave  ...                             http://www.carlsjr.com

[10000 rows x 10 columns]

**Filtrar una COLUMNA, para analizar un parte del df**

*Traer los datos de **UNA** columna en específico / df["nombre_columna"]*

In [ ]:
df["country"]

0       US
1       US
2       US
3       US
4       US
        ..
9995    US
9996    US
9997    US
9998    US
9999    US
Name: country, Length: 10000, dtype: object

*Traer datos de **VARIAS** columnas en específico / df[["name_column1","nc2",...]]*

In [ ]:
df[["country", "city"]]

     country                    city
0         US                 Massena
1         US  Washington Court House
2         US               Maysville
3         US                 Massena
4         US                  Athens
...      ...                     ...
9995      US                 Augusta
9996      US                    Cary
9997      US                Longmont
9998      US          Cathedral City
9999      US                 Anaheim

[10000 rows x 2 columns]

**Filtrado por FILA**

**UNA** fila según índice

In [ ]:
df.iloc[0]

address                                             324 Main St
city                                                    Massena
country                                                      US
keys                        us/ny/massena/324mainst/-1161002137
latitude                                                44.9213
longitude                                              -74.8902
name                                                 McDonald's
postalCode                                                13662
province                                                     NY
websites      http://mcdonalds.com,http://www.mcdonalds.com/...
Name: 0, dtype: object

**VARIAS** filas segun el índice, slice / el df.head(num) es un caso especial porque solo traer las primeras num filas, este caso con el slice traes las que quieras

In [ ]:
df[2:5]

                    address  ...                                           websites
0               324 Main St  ...  http://mcdonalds.com,http://www.mcdonalds.com/...
1           530 Clinton Ave  ...                              http://www.wendys.com
2      408 Market Square Dr  ...  http://www.frischs.com,https://www.frischs.com...
3     6098 State Highway 37  ...  http://mcdonalds.com,http://www.mcdonalds.com/...
4           139 Columbus Rd  ...  http://www.omgrotisserie.com,http://omgrotisse...
...                     ...  ...                                                ...
9995  3013 Peach Orchard Rd  ...            http://www.wendys.com,http://wendys.com
9996      678 Northwest Hwy  ...                           http://www.mcdonalds.com
9997           1708 Main St  ...                                http://fiveguys.com
9998      67740 Highway 111  ...  http://www.elpolloloco.com,http://elpolloloco.com
9999    5701 E La Palma Ave  ...                             http://www.carlsjr.com

[10000 rows x 10 columns]

*Traer **INDIVIDUALMENTE** / df.iloc[[indice1, indice2, etc]]*

In [ ]:
#Devuelve un valor
df_filtrado = df.iloc[[0,5,17]]
df_filtrado

                    address  ...                                           websites
0               324 Main St  ...  http://mcdonalds.com,http://www.mcdonalds.com/...
1           530 Clinton Ave  ...                              http://www.wendys.com
2      408 Market Square Dr  ...  http://www.frischs.com,https://www.frischs.com...
3     6098 State Highway 37  ...  http://mcdonalds.com,http://www.mcdonalds.com/...
4           139 Columbus Rd  ...  http://www.omgrotisserie.com,http://omgrotisse...
...                     ...  ...                                                ...
9995  3013 Peach Orchard Rd  ...            http://www.wendys.com,http://wendys.com
9996      678 Northwest Hwy  ...                           http://www.mcdonalds.com
9997           1708 Main St  ...                                http://fiveguys.com
9998      67740 Highway 111  ...  http://www.elpolloloco.com,http://elpolloloco.com
9999    5701 E La Palma Ave  ...                             http://www.carlsjr.com

[10000 rows x 10 columns]

**VARIOS** segun key

In [ ]:
#df.loc[[key1, key2, ...]]

**Filtrado de FILAS y COLUMNAS / df.loc[[indice1, indiceN], ["name_column1", "name_column2" ]]**

In [ ]:
#Devulve el filtrado, no modifica el df original
df_filtrado = df.loc[[0,1,4],["latitude", "longitude"]]
df_filtrado

   latitude  longitude
0  44.92130  -74.89021
1  39.53255  -83.44526
4  39.35155  -82.09728

**Filtrar FILAS segun alguna condicion de las COLUMNAS / df[df["colum"] > valor]**

In [ ]:
#Del dataframe has un filtrado a la columna latitude que sea mayor a valor, devulve un valor, no modifica el df original
#df_filtrado = df[df["latitude"] > 39.41760]
#df_filtrado
df_filtrado = df[(df["latitude"] > 39.41760) & (df["longitude"] < -83.445260)]
df_filtrado
# or == |

                     address  ...                                           websites
6              590 S Main St  ...  https://www.dominos.com/en/?redirect=homepagea...
30       105 Business Loop W  ...  http://www.tacobell.com,https://locations.taco...
31      1531 University Dr S  ...  https://www.dominos.com/en/?redirect=homepage,...
32            718 10th St SE  ...  https://www.tacojohns.com,http://locations.tac...
33          1400 24th Ave SW  ...  http://mcdonalds.com,http://www.mcdonalds.com/...
...                      ...  ...                                                ...
9989       1120 S Haynes Ave  ...  http://mcdonalds.com,http://www.mcdonalds.com/...
9991  1122 SE Hawthorne Blvd  ...                         http://www.burgerville.com
9993         3956 Guthrie St  ...  http://www.whitecastle.com,http://whitecastle.com
9996       678 Northwest Hwy  ...                           http://www.mcdonalds.com
9997            1708 Main St  ...                                http://fiveguys.com

[2356 rows x 10 columns]

**Filtrado por condicion, a partir de una cadena incluida en el valor**

In [ ]:

#trae los que tengan incluido un valor str "nal" en la propiedad name
df[df["name"].str.contains("nal")]

                    address  ...                                           websites
0               324 Main St  ...  http://mcdonalds.com,http://www.mcdonalds.com/...
3     6098 State Highway 37  ...  http://mcdonalds.com,http://www.mcdonalds.com/...
7         401 N Jennings St  ...                           http://www.mcdonalds.com
12          1535 NW 50th St  ...  http://mcdonalds.com,http://www.mcdonalds.com/...
15      301 University Blvd  ...  http://mcdonalds.com,http://www.mcdonalds.com/...
...                     ...  ...                                                ...
9969        601 Aberdeen Rd  ...  http://mcdonalds.com,http://www.mcdonalds.com/...
9978              Us Hwy 29  ...                                                NaN
9979      50 New Orleans Rd  ...  http://mcdonalds.com,http://www.mcdonalds.com/...
9985      820 City Park Ave  ...                               http://mcdonalds.com
9989      1120 S Haynes Ave  ...  http://mcdonalds.com,http://www.mcdonalds.com/...

[2124 rows x 10 columns]

In [ ]:
df["latitude"]

0       44.921300
1       39.532550
2       38.627360
3       44.950080
4       39.351550
          ...
9995    33.415257
9996    42.217300
9997    40.189190
9998    33.788640
9999    33.860074
Name: latitude, Length: 10000, dtype: float64